import os
import re
import json
from dotenv import load_dotenv
from google import genai

# ENVIRONMENT CONFIG
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment variables")

client = genai.Client(api_key=GEMINI_API_KEY)

MODEL_NAME = "gemini-2.5-flash"

# GLOBAL DISCLAIMER
DISCLAIMER = (
    "This information is generated by an AI system and is provided "
    "for general informational purposes only. It does not constitute "
    "legal advice. Please consult a licensed advocate for professional "
    "legal assistance."
)

# GEMINI CORE CALL
def ask_gemini(prompt: str):

    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if response and response.text:
            return response.text.strip()

    except Exception as e:
        print("Gemini API Error:", e)

    return None

# JSON EXTRACTION HELPER
def extract_json(text):

    if not text:
        return None

    match = re.search(r"\{.*\}", text, re.DOTALL)

    if not match:
        return None

    cleaned = match.group(0)

    cleaned = re.sub(r",\s*}", "}", cleaned)
    cleaned = re.sub(r",\s*]", "]", cleaned)

    try:
        return json.loads(cleaned)
    except:
        return None

# CHATBOT RESPONSE GENERATOR
def generate_reply(user_message: str):

    prompt = f"""
You are Virtual Advocate AI, an Indian legal information assistant.

Respond ONLY in valid JSON.

JSON FORMAT:

{{
"summary":"",
"applicable_laws":[],
"legal_options":[],
"next_steps":[],
"note":""
}}

User Query:
{user_message}
"""

    response = ask_gemini(prompt)

    parsed = extract_json(response)

    if parsed:
        parsed["note"] = DISCLAIMER
        return parsed

    return {
        "summary": response or "Unable to process request.",
        "applicable_laws": [],
        "legal_options": [],
        "next_steps": [],
        "note": DISCLAIMER
    }

# AI LEGAL CATEGORY CLASSIFIER
def classify_with_ai(issue_text: str):

    prompt = f"""
You are an AI system that classifies Indian legal issues.

Classify the issue into EXACTLY ONE of the following categories:

Criminal
Family
Consumer
Civil

Definitions:

Criminal:
Offences punishable under criminal law such as
murder, assault, rape, theft, fraud, cyber crime,
harassment, threats.

Family:
Disputes involving marriage, divorce, custody,
domestic violence, maintenance, family conflicts.

Consumer:
Issues related to defective products, refund problems,
service complaints, online shopping disputes.

Civil:
Property disputes, contract disputes, land ownership
issues, employment disputes, money recovery.

STRICT RULES:
Return ONLY the category name.

Issue:
{issue_text}
"""

    result = ask_gemini(prompt)

    allowed = ["Criminal", "Family", "Consumer", "Civil"]

    if result and result.strip() in allowed:
        return result.strip(), "AI-Detected"

    if result:
        for cat in allowed:
            if cat.lower() in result.lower():
                return cat, "AI-Detected"

    return "Civil", "Low"

# AI LEGAL GUIDANCE GENERATOR
def generate_ai_guidance(category: str, issue_text: str):

    prompt = f"""
Provide legal guidance for this issue.

Return JSON format:

{{
"law":"",
"advice":"",
"procedure":[],
"note":""
}}

Category: {category}
Issue: {issue_text}
"""

    response = ask_gemini(prompt)

    parsed = extract_json(response)

    if parsed:
        parsed["note"] = DISCLAIMER
        return parsed

    return {
        "law": "General Indian Law",
        "advice": response or "More information is required.",
        "procedure": ["Consult a licensed advocate"],
        "note": DISCLAIMER
    }